Title
========================================================

```{r}
oldwd = getwd()

setwd("/mnt/hgfs/WorkSpaces/data_science/Getting_and_Cleaning_Data/quizzes")

```


## Q1

```{r}
fileUrl = "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv "
download.file(fileUrl,destfile="./data/q1.csv",method="curl")
list.files("./data")

housingdata <- read.table(file="./data/q1.csv",sep=',',head=TRUE)
dim(housingdata)
head(housingdata)
length(which(housingdata$VAL==24))

sum(!is.na(housingdata$VAL[housingdata$VAL==24]))

table(housingdata$VAL)


housingdata$FES


```



## Q3

```{r}
fileUrl = "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FDATA.gov_NGAP.xlsx "
download.file(fileUrl,destfile="./data/q3.xlsx",method="curl")
list.files("./data")

row <- 18:23
col <- 7:15

dat  <- read.xlsx(file="./data/q3.xlsx",head = TRUE, sheetIndex=1,rowIndex=row,colIndex=col)

dat 

 sum(dat$Zip*dat$Ext,na.rm=T) 

```



## Q4

```{r}
fileUrl = "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml"
download.file(fileUrl,destfile="./data/q4.xml",method="curl")
list.files("./data")

doc <- xmlTreeParse(file="./data/q4.xml", useInternal=TRUE)
rootNode <- xmlRoot(doc)
xpathSApply(rootNode, "//name", xmlValue)
xpathSApply(rootNode, "//zipcode", xmlValue)
nums <- sum(xpathSApply(rootNode, "//zipcode", xmlValue)==21231)
nums

```

## Q5

```{r}
fileUrl = "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv"
download.file(fileUrl,destfile="./data/q5.csv",method="curl")
list.files("./data")

DT <-fread(input="./data//q5.csv")

dim(DT)
head(DT)


DT[,mean(pwgtp15),by=SEX]


system.time(DT[,mean(pwgtp15),by=SEX])
system.time(mean(DT[DT$SEX==1,]$pwgtp15))+system.time(mean(DT[DT$SEX==2,]$pwgtp15))
system.time(sapply(split(DT$pwgtp15,DT$SEX),mean))
system.time(mean(DT$pwgtp15,by=DT$SEX))
system.time(tapply(DT$pwgtp15,DT$SEX,mean))
system.time(rowMeans(DT)[DT$SEX==1])+system.time(rowMeans(DT)[DT$SEX==2]
)


#A
st = proc.time()
for (i in 1:100){
  sapply(split(DT$pwgtp15,DT$SEX),mean)
}
print (proc.time() - st)

#B
st = proc.time()
for (i in 1:100){
  rowMeans(DT)[DT$SEX==1];rowMeans(DT)[DT$SEX==2]
}
print (proc.time() - st)

#C
st = proc.time()
for (i in 1:100){
  mean(DT$pwgtp15,by=DT$SEX)
}
print (proc.time() - st)

#D
st = proc.time()
for (i in 1:100){
  tapply(DT$pwgtp15,DT$SEX,mean)
}
print (proc.time() - st)

#E
st = proc.time()
for (i in 1:100){
  mean(DT[DT$SEX==1,]$pwgtp15);mean(DT[DT$SEX==2,]$pwgtp15)
}
print (proc.time() - st)

#F
st = proc.time()
for (i in 1:100){
  DT[,mean(pwgtp15),by=SEX]
}
print (proc.time() - st)

```

```{r fig.width=7, fig.height=6}
plot(cars)
```

